# Cloud Build configuration for GKE deployment with Artifact Registry

steps:
  # Step 1: Build and package the application using Maven
  - name: 'maven:3.9-eclipse-temurin-17'
    id: 'maven-build'
    entrypoint: mvn
    args: ['clean', 'package', '-DskipTests']

  # Step 2: Build Docker image and tag for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:$SHORT_SHA',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:latest',
      '.'
    ]

  # Step 3: Push image with commit SHA tag to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push-sha'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:$SHORT_SHA']

  # Step 4: Push image with latest tag to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push-latest'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:latest']

  # Step 5: Get GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-gke-credentials'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_GKE_CLUSTER_NAME}'
      - '--region=${_GKE_REGION}'
      - '--project=$PROJECT_ID'

  # Step 6: Create processed kustomization with actual values
  - name: 'ubuntu'
    id: 'process-kustomization'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a new kustomization.yaml with actual values
        cat > k8s/kustomization.yaml << EOF
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization

        resources:
          - redis-deployment.yaml
          - redis-service.yaml
          - loadbalancer-deployment.yaml

        images:
          - name: dynamic-loadbalancer-placeholder
            newName: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}
            newTag: $SHORT_SHA
        EOF
        
        echo "=== Generated Kustomization ==="
        cat k8s/kustomization.yaml

  # Step 7: Preview what will be deployed (optional but helpful)
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'preview-manifests'
    args: ['kustomize', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'

  # Step 8: Deploy with Kustomize
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-with-kustomize'
    args: ['apply', '-k', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'

  # Step 9: Wait for rollout
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'wait-for-rollout'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/dynamic-loadbalancer'
      - '--timeout=5m'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'

# Substitution variables
substitutions:
  _REGION: 'europe-west1'
  _ARTIFACT_REGISTRY_REPO: 'loadbalancer-sandbox'
  _IMAGE_NAME: 'dynamic-loadbalancer'
  _GKE_CLUSTER_NAME: 'autopilot-cluster-1'
  _GKE_REGION: 'europe-west1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:latest'

timeout: 1200s