# Cloud Build configuration for GKE deployment with Artifact Registry
# This builds the Docker image and pushes it to Artifact Registry

steps:
  # Step 1: Build and package the application using Maven
  - name: 'maven:3.9-eclipse-temurin-17'
    id: 'maven-build'
    entrypoint: mvn
    args: ['clean', 'package', '-DskipTests']

  # Step 2: Build Docker image and tag for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:$SHORT_SHA',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:latest',
      '.'
    ]

  # Step 3: Push image with commit SHA tag to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push-sha'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:$SHORT_SHA']

  # Step 4: Push image with latest tag to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push-latest'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:latest']

  # Step 5: Get GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-gke-credentials'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_GKE_CLUSTER_NAME}'
      - '--region=${_GKE_REGION}'  # Changed from --zone
      - '--project=$PROJECT_ID'

  # Step 6: Deploy Redis (if not already deployed)
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-redis'
    args: [ 'apply', '-f', 'k8s/redis-deployment.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-redis-service'
    args: [ 'apply', '-f', 'k8s/redis-service.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'

  # Step 7: Deploy your application
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-app'
    args: [ 'apply', '-f', 'k8s/loadbalancer-deployment.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'

# Substitution variables - replace these with your values
substitutions:
  _REGION: 'europe-west1'
  _ARTIFACT_REGISTRY_REPO: 'loadbalancer-sandbox'
  _IMAGE_NAME: 'dynamic-loadbalancer'
  _GKE_CLUSTER_NAME: 'autopilot-cluster-1'
  _GKE_REGION: 'europe-west1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

# Images to be pushed (for Cloud Build dashboard)
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:latest'

timeout: 1200s