version: '3.8'

services:
  # Redis for shared state management
  redis:
    image: redis:7-alpine
    container_name: redis-state
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - loadbalancer-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # Load Balancer Instance 1
  loadbalancer1:
    build: .
    container_name: loadbalancer-app-1
    ports:
      - "8091:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INSTANCE_ID=lb-instance-1
    volumes:
      - nginx-config:/nginx-config
    networks:
      - loadbalancer-network
    depends_on:
      redis:
        condition: service_healthy
      nginx:
        condition: service_started
      backend1:
        condition: service_started
      backend2:
        condition: service_started
      backend3:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/loadbalancer/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Load Balancer Instance 2
  loadbalancer2:
    build: .
    container_name: loadbalancer-app-2
    ports:
      - "8092:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INSTANCE_ID=lb-instance-2
    volumes:
      - nginx-config:/nginx-config
    networks:
      - loadbalancer-network
    depends_on:
      redis:
        condition: service_healthy
      nginx:
        condition: service_started
      backend1:
        condition: service_started
      backend2:
        condition: service_started
      backend3:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/loadbalancer/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # NGINX Load Balancer
  nginx:
    build: ./nginx
    container_name: nginx-lb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-config:/etc/nginx/conf.d
      - nginx-logs:/var/log/nginx
    networks:
      - loadbalancer-network
    depends_on:
      - backend1
      - backend2
      - backend3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  loadbalancer-network:
    driver: bridge

volumes:
  nginx-config:
  nginx-logs:
  redis-data: