server:
  port: 8080

spring:
  application:
    name: dynamic-nginx-loadbalancer

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 10000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000
      # Enable connection validation
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5 minutes default TTL
      cache-null-values: false
      key-prefix: "loadbalancer:"

loadbalancer:
  servers:
    - id: server1
      host: pi-gateway-kcop3cwgaq-ew.a.run.app/ci/api/v1
      port:
      name: "Backend Server 1"
    - id: server2
      host: qlf-agentapi-eme.gutouch.net/pda/pi
      port:
      name: "Backend Server 2"

  nginx:
    config-dir: "/nginx-config"
    config-file: "upstream.conf"
    reload-command: "nginx -s reload"
    upstream-name: "backend"

  weight-factors:
    response-time: 0.25
    error-rate: 0.25
    timeout-rate: 0.15
    uptime: 0.20
    degradation: 0.15

  redis:
    # Keys configuration
    keys:
      metrics-prefix: "metrics:"
      config-prefix: "config:"
      weights-prefix: "weights:"
      nginx-config-key: "nginx:current-config"
      last-update-key: "nginx:last-update"

    # TTL configuration (in seconds)
    ttl:
      metrics: 600          # 10 minutes
      config: 3600          # 1 hour
      weights: 300          # 5 minutes
      nginx-config: 1800    # 30 minutes

    intervals:
      config-sync: 10000    # Sync config every 10 seconds
      metrics-cleanup: 60000 # Cleanup old metrics every minute

  simulation:
    enabled: false
    interval-seconds: 60
    metrics-variation: 0.2

logging:
  level:
    com.loadbalancer: INFO
    org.springframework.data.redis: DEBUG
    io.lettuce.core: INFO