server:
  port: 8090

spring:
  application:
    name: dynamic-nginx-loadbalancer

  # Redis Configuration for Docker
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 10000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 0
      cache-null-values: false
      key-prefix: "loadbalancer:"

# Load Balancer Configuration for Docker
loadbalancer:
  # INCOMING servers configuration (original servers)
  servers:
    - id: server1
      host: pi-gateway-kcop3cwgaq-ew.a.run.app/ci/api/v1
      port:
      name: "Incoming Backend Server 1"
      enabled: true
    - id: server2
      host: qlf-agentapi-eme.gutouch.net/pda/pi
      port:
      name: "Incoming Backend Server 2"
      enabled: true

  # OUTGOING servers configuration (new separate servers)
  outgoing-servers:
    - id: outgoing1
      host: backend-a-971441253898.europe-west1.run.app
      port:
      name: "Outgoing Backend Server 1"
      enabled: true
    - id: outgoing2
      host: backend-b-971441253898.europe-west1.run.app
      port:
      name: "Outgoing Backend Server 2"
      enabled: true

  nginx:
    config-dir: "/nginx-config"
    config-file: "upstream.conf"
    reload-command: "nginx -s reload"
    upstream-name: "backend"
    # Support for dual upstreams
    incoming-upstream-name: "backend_incoming"
    outgoing-upstream-name: "backend_outgoing"

  weight-factors:
    response-time: 0.25
    error-rate: 0.25
    timeout-rate: 0.15
    uptime: 0.20
    degradation: 0.15

  # Redis State Management Configuration
  redis:
    keys:
      metrics-prefix: "metrics:"
      config-prefix: "config:"
      weights-prefix: "weights:"
      nginx-config-key: "nginx:current-config"
      last-update-key: "nginx:last-update"
      instance-prefix: "instance:"
      lock-prefix: "lock:"
      # New keys for dual upstream support
      incoming-weights-prefix: "weights:incoming:"
      outgoing-weights-prefix: "weights:outgoing:"

    ttl:
      metrics: 600          # 10 minutes
      config: 3600          # 1 hour
      weights: 300          # 5 minutes
      nginx-config: 1800    # 30 minutes
      instance-heartbeat: 60 # 1 minute

    intervals:
      config-sync: 10000    # Sync config every 10 seconds
      metrics-cleanup: 60000 # Cleanup old metrics every minute
      heartbeat: 30000      # Heartbeat every 30 seconds

  simulation:
    enabled: false
    interval-seconds: 60
    metrics-variation: 0.2

logging:
  level:
    root: INFO
    com.intouch.cp.lb_aip_pidirect: INFO
    org.springframework.data.redis: DEBUG
    io.lettuce.core: INFO