server:
  port: 8080

spring:
  application:
    name: dynamic-nginx-loadbalancer

  datasource:
    url: jdbc:h2:mem:loadbalancer
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: true

loadbalancer:
  servers:
    - id: server1
      host: backend-a-971441253898.europe-west1.run.app
      port: 443
      name: "Backend Server 1"
    - id: server2
      host: backend-b-971441253898.europe-west1.run.app
      port: 443
      name: "Backend Server 2"
    - id: server3
      host: backend-c-971441253898.europe-west1.run.app
      port: 443
      name: "Backend Server 3"

  nginx:
    config-path: "/nginx-config/upstream.conf"
    reload-command: "nginx -s reload"
    upstream-name: "backend"

  weight-factors:
    response-time: 0.25
    error-rate: 0.25
    timeout-rate: 0.15
    uptime: 0.20
    degradation: 0.15

  simulation:
    enabled: false
    interval-seconds: 60
    metrics-variation: 0.2

logging:
  level:
    com.loadbalancer: INFO
    org.springframework.scheduling: DEBUG