apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-loadbalancer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dynamic-loadbalancer
  template:
    metadata:
      labels:
        app: dynamic-loadbalancer
    spec:
      # Add service account if needed for image pull
      # serviceAccountName: default
      containers:
        - name: dynamic-loadbalancer
          image: dynamic-loadbalancer-placeholder
          imagePullPolicy: Always  # Force pull latest image
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          # Add readiness probe
          readinessProbe:
            httpGet:
              path: /actuator/health  # Adjust based on your app
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Add liveness probe
          livenessProbe:
            httpGet:
              path: /actuator/health  # Adjust based on your app
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"